project/core/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views
from .forms import LoginForm
from django.contrib.auth import views as auth_views

app_name = "core"

urlpatterns = [
    path('', views.index, name="index"),
    path('contact/', views.contact, name="contact"),
    path('signup/', views.signup, name="signup"),
    path('login/', auth_views.LoginView.as_view(template_name="core/login.html", authentication_form=LoginForm), name="login"),
]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
]

project/core/models.py
from django.db import models

# Create your models here.

project/core/forms.py
from django import forms

from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        "placeholder": "your username",
        "class": "input-field"
    }))

    password = forms.CharField(widget=forms.PasswordInput(attrs={
        "placeholder": "your password",
        "class": "input-field"
    }))

class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')
        
    username = forms.CharField(widget=forms.TextInput(attrs={
        "placeholder": "create a username",
        "class": "input-field"
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        "placeholder": "enter your email address",
        "class": "input-field"
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        "placeholder": "create a password",
        "class": "input-field"
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        "placeholder": "re-enter the password",
        "class": "input-field"
    }))

project/core/views.py
from django.shortcuts import render, redirect

from .forms import SignupForm
# Create your views here.
def index(request):
    return render(request, "core/index.html", {})

def contact(request):
    return render(request, "core/contact.html", {})

def signup(request):
    if request.method == "POST":
        form = SignupForm(request.POST)
        
        if form.is_valid():
            form.save()
            
            return redirect('/login/')
    else:
        form = SignupForm()
    
    return render(request, "core/signup.html", {
        "form": form
    })

project/core/templates/base.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Chakra+Petch&display=swap" rel="stylesheet">

        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Poppins&family=Roboto&display=swap" rel="stylesheet">

        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Open+Sans&display=swap" rel="stylesheet">
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title> {% block title %}{% endblock title %} | DUKA</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        {% load static %}
        <link rel="stylesheet" href="{% static 'base.css' %}">
        {% load static %}
        <link rel="stylesheet" href="{% static 'navbar_footer.css' %}">
    </head>
    <body>
        <nav class="navbar">
            <a href="{% url 'core:index' %}" class="links logo">DUKA</a>
            <ul class="navlink-container">
                <li class="lists"><a href="#" class="links navlinks navlink">New Item</a></li>
                <li class="lists"><a href="#" class="links navlinks navlink">Browse</a></li>
                <li class="lists"><a href="{% url 'core:signup' %}" class="links navlinks teal-btn">Sign Up</a></li>
                <li class="lists"><a href="{% url 'core:login' %}" class="links navlinks gray-btn">Log In</a></li>
            </ul>
        </nav>
        {% block content %}
        
        {% endblock content %}
        <footer class="footer">
            <div class="about-section">
                <h3 class="header-two footer-header">About</h3>
                <p>This is my first ecommerce project using Django Framework. Cool 😁</p>
            </div>
            <div class="menu-section">
                <h3 class="header-two footer-header">Menu</h3>
                <ul>
                    <li class="lists"><a href="{% url 'core:index' %}" class="links footer-link">Home</a></li>
                    <li class="lists"><a href="{% url 'core:contact' %}" class="links footer-link">Contact</a></li>
                    <li class="lists"><a href="#" class="links footer-link">Privacy Policy</a></li>
                    <li class="lists"><a href="#" class="links footer-link">Terms of Use</a></li>
                </ul>
            </div>
        </footer>


    </body>
</html>

project/core/templates/core/contact.html
{% extends 'base.html' %}

{% block title %}contact{% endblock title %}

{% block content %}
<head></head>
<h1>Contact Page</h1>
{% endblock content %}

project/core/templates/core/index.html
{% extends 'base.html' %}

{% block title %}Welcome{% endblock title %}

{% block content %}
<head></head>
<h1 class="headers">Home Page</h1>
<h1 class="header-two">Home Page</h1>

{% endblock content %}

project/core/templates/core/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock title %}

{% block content %}
<head></head>
<h1>Login</h1>
<form action="{% url 'core:login' %}" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit" class="gray-btn">submit</button>
    </br>
    {% if form.errors or form.non_field_errors %}
        <div>
            {% for field in form.errors %}
                {{field.errors}}
            {% endfor %}

            {{form.non_field_errors}}
        </div>
    {% endif %}
</form>
{% endblock content %}

project/core/templates/core/signup.html
{% extends 'base.html' %}

{% block title %}Signup{% endblock title %}

{% block content %}
<head></head>
<h1>Signup</h1>
<form action="{% url 'core:signup' %}" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit" class="teal-btn">submit</button>
    </br>
    {% if form.errors or form.non_field_errors %}
        <div>
            {% for field in form.errors %}
                {{field.errors}}
            {% endfor %}

            {{form.non_field_errors}}
        </div>
    {% endif %}
</form>
{% endblock content %}